[project]
name = "ak-py-bootstrap"
description = "Provides functionality for generating skeletons for Python projects."
readme = "README.md"
requires-python = ">=3.13"
license = "Apache-2.0"
license-files = ["LICEN[CS]E*", "AUTHORS.md"]
authors = [{name = "Aliaksandr Karotki", email = "abkorotky@gmail.com"}]
keywords = ["bootstrap", "python", "project", "template"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Framework :: tox",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.13",
    "Topic :: Utilities",
]
dynamic = ["version"]
dependencies = []

[project.entry-points.py_bootstrap_templates]
py_bootstrap = "py_bootstrap.templates"

[project.urls]
documentation = "https://ak-py-bootstrap.readthedocs.io/"
repository = "https://github.com/ABKorotky/py-bootstrap.git"
changelog = "https://github.com/ABKorotky/py-bootstrap/blob/main/CHANGELOG.md"

[project.scripts]
bootstrap = "py_bootstrap.scripts.bootstrap:main"

[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
]
build-backend = "setuptools.build_meta"

[dependency-groups]
test = ["coverage"]
tox = ["tox>=4.22"]
format = [
    "black",
    "isort"
]
cs = [
    {include-group = "format"},
    "flake8",
    "flake8-pyproject"
]
ann = ["mypy"]
doc = [
    "sphinx>=7",
    "sphinx-rtd-theme>=3",
    "myst-parser>=2",
    "sphinx-argparse>=0.4",
]
changelog = ["towncrier"]
scm = [
    "setuptools",
    "setuptools-scm"
]
dist = [
    "build",
    "twine"
]
release = [
    {include-group = "changelog"},
    {include-group = "scm"},
    {include-group = "dist"},
]
dev = [
    {include-group = "test"},
    {include-group = "format"},
    {include-group = "cs"},
    {include-group = "ann"},
    {include-group = "doc"},
    {include-group = "release"},
    "pre-commit",
    "tox>=4.22",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["py_bootstrap*"]

[tool.setuptools.package-data]
"*" = [
    "*.tmpl",
    "make.bat",
    "Makefile",
    "*.txt",
]

[tool.setuptools_scm]

[tool.black]
target-version = ['py313']
line-length = 80

[tool.isort]
profile = "black"
py_version=313
skip = [".git", ".tox", ".venv"]

[tool.flake8]
exclude = [".git", ".tox", ".venv"]
max-line-length = 88
extend-ignore = ["E203", "E701"]
import-order-style = "pep8"
application-import-names = ["py_bootstrap"]

[tool.mypy]
check_untyped_defs = true
exclude = "/(.venv|templates|tst_templates)"
files = "**/*.py"
follow_imports = "silent"
ignore_missing_imports = true
python_version = "3.13"
show_error_codes = true
show_error_context = true

[[tool.mypy.overrides]]
module = "tests.*"
disable_error_code = [
    "arg-type",
    "assignment",
    "attr-defined",
    "method-assign",
]

[tool.coverage.run]
omit = ["tests/*"]
source = ["py_bootstrap"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if t.TYPE_CHECKING:",
    "if __name__ == .__main__.:",
]
fail_under = 95
omit = ["tests/*"]

[tool.towncrier]
package_dir = "py_bootstrap"
directory = "changelog.d"
filename = "CHANGELOG.md"
start_string = "<!-- towncrier release notes start -->\n"
title_format = "## [{version}] - {project_date}"
issue_format = "[#{issue}](https://github.com/ABKorotky/py-bootstrap/issues/{issue})"
underlines = ["", "", ""]
wrap = false
template = "changelog.d/_template.md"
ignore = ["README.md", "_template.md"]

[[tool.towncrier.type]]
directory = "added"
name = "Added"
showcontent = true

[[tool.towncrier.type]]
directory = "changed"
name = "Changed"
showcontent = true

[[tool.towncrier.type]]
directory = "deprecated"
name = "Deprecated"
showcontent = true

[[tool.towncrier.type]]
directory = "fixed"
name = "Fixed"
showcontent = true

[[tool.towncrier.type]]
directory = "removed"
name = "Removed"
showcontent = true

[[tool.towncrier.type]]
directory = "security"
name = "Security"
showcontent = true
