[tox]
requires = tox>=4.22
env_list =
    py313
    py314
skip_missing_interpreters = true


[testenv]
description = "Runs the test suite under coverage on {base_python}"
dependency_groups = test
commands =
    coverage run --module unittest discover tests
    coverage report
    coverage xml
    coverage html
